services:
  plebiq-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SITE_URL=https://plebiq.com
    container_name: plebiq-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://plebiq.com
    env_file:
      - .env.production
    ports:
      - "3000:3000"
